import 'size_config.dart';

class AppDimen {
  /*HORIZONTAL SPACE*/
  static final double H_DIMEN_400 = 97.92 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_360 = 86.92 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_350 = 79.92 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_300 = 70.92 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_270 = 69.10 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_260 = 65.10 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_250 = 59.10 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_240 = 55.10 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_210 = 50.10 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_200 = 47.28 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_180 = 42.55 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_170 = 40.20 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_160 = 37.82 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_150 = 35.46 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_140 = 32.57 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_130 = 30.57 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_125 = 29.57 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_120 = 28.57 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_115 = 27.57 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_110 = 25.87 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_100 = 23.64 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_95 = 22.94 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_90 = 21.28 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_80 = 18.91 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_75 = 17.73 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_64 = 15.13 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_60 = 14.18 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_55 = 13 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_50 = 12 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_45 = 10.8 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_40 = 10 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_35 = 8.4 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_30 = 7.2 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_25 = 6 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_20 = 4.8 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_15 = 3.6 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_12 = 3 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_10 = 2.5 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_8 = 2 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_5 = 1.18 * SizeConfig.safeBlockHorizontal;
  static final double H_DIMEN_3 = 0.70 * SizeConfig.safeBlockHorizontal;

  /*VERTICAL SPACE*/

  static final double V_DIMEN_600 = 90.98 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_580 = 88.98 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_550 = 80.98 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_500 = 65.98 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_450 = 57.98 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_400 = 51.55 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_360 = 49.55 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_350 = 45.10 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_320 = 40.66 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_300 = 38.66 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_270 = 36.5 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_260 = 34 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_250 = 33 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_230 = 29.12 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_220 = 27.88 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_200 = 25.77 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_180 = 23.19 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_160 = 20.61 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_150 = 19.32 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_100 = 12.88 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_90 = 11.88 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_80 = 10.31 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_70 = 9.02 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_65 = 8.37 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_64 = 8.24 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_60 = 7.73 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_58 = 7.47 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_55 = 7.08 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_50 = 6.5 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_47 = 6.05 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_45 = 5.8 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_40 = 5.2 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_35 = 4.6 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_30 = 3.9 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_25 = 3.2 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_20 = 2.5 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_18 = 2.32 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_15 = 1.93 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_10 = 1.9 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_8 = 1.03 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_5 = 0.65 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_3 = 0.38 * SizeConfig.safeBlockVertical;
  static final double V_DIMEN_2 = 0.25 * SizeConfig.safeBlockVertical;

  /*ICON SIZE*/
  static final double ICON_SIZE_16 = 3.78 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_18 = 4.4 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_20 = 4.73 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_22 = 5.3 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_25 = 5.91 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_28 = 6.61 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_30 = 7.09 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_35 = 8.27 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_40 = 9.45 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_45 = 10.65 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_50 = 11.82 * SizeConfig.safeBlockHorizontal;
  static final double ICON_SIZE_55 = 13.00 * SizeConfig.safeBlockHorizontal;

  /*TEXT SIZES*/
  static final double TEXT_SIZE_11 = 2.60 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_12 = 3 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_14 = 3.4 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_15 = 3.6 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_16 = 3.8 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_17 = 4.2 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_18 = 4.4 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_20 = 4.8 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_22 = 5.4 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_24 = 5.4 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_26 = 6.15 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_30 = 6.97 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_35 = 7.97 * SizeConfig.safeBlockHorizontal;
  static final double TEXT_SIZE_40 = 8.16 * SizeConfig.safeBlockHorizontal;
}
